// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "Maxwell Steel",
    "description": "Decades of Steel, Unmatched Quality."
  },

  "Header": {
    "links": {
      "link-1": "Products",
      "link-2": "Why Us",
      "link-3": "About us",
      "link-4": "Blog"
    },
    "button": "Contact us"
  },

  "Products": {
    "title": "Products",
    "features": "Features",
    "specifications": "Specifications"
  },

  "Footer": {
    "links": {
      "link-1": "Products",
      "link-2": "Why Us",
      "link-3": "About us",
      "link-4": "Blog",
      "link-5": "Contact us"
    },

    "copyright": "All rights reserved."
  },

  "Testimonials": {
    "title": "Testimonials"
  },

  "Contact": {
    "title": "Contact Us",

    "form": {
      "name": "Name",
      "email": "Email",
      "phone": "Phone",
      "message": "Message",
      "button": "Send"
    },

    "messages": {
      "success": {
        "title": "Message Sent Successfully",
        "description": "Thank you for contacting us. We will get back to you as soon as possible."
      },
      "error": {
        "title": "Sending Failed",
        "description": "An error occurred while sending the message. Please try again."
      }
    }
  },

  "Blog": {
    "title": "Blog",
    "read-more": "Read more",
    "not-found": "No articles are currently available",

    "post": {
      "return": "Return to the blog",
      "not-found": "The article does not exist."
    },

    "close": "Close"
  }
};
export default messages;